# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_negative_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='neg_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof', models.CharField(max_length=10)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='in_elements',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
