# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170109_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='summary',
            field=models.CharField(default='', max_length=150),
        ),
    ]
