# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_latest_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='summary',
            field=models.CharField(max_length=150),
        ),
    ]
